---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-merge-conflict
  - repo: https://github.com/prettier/prettier
    rev: 2.0.5
    hooks:
      - id: prettier
        types: [markdown]
  - repo: local
      # Prose (speech or writing) Linter
      - id: proselint
        name: proselint
        description: An English prose (speech or writing) linter
        entry: proselint
        language: system
        types: [ rst, markdown ]
        additional_dependencies: [proselint]
